import MindMap from '@/components/MindMap';

import { Nodes } from '@/constant/nodeType';

const nodes: Nodes = {
  '나의 일상': {
    value: '나의 일상',
    x: 0,
    y: 0,
    link: '/paper/나의-일상',
    edges: ['디미고', '../', '문화'],
    circleSize: 60,
    isFolder: true,
  },
  디미고: {
    value: '디미고',
    x: 30,
    y: 100,
    link: '/paper/dimigo',
    edges: ['2학년 1, 2일', 'AI Club 🌿Fregic'],
    circleSize: 30,
  },
  문화: {
    value: '문화',
    x: -70,
    y: -60,
    link: '/paper/나의-일상',
    edges: ['영화', '뮤지컬'],
    circleSize: 30,
    isFolder: true,
  },
  영화: {
    value: '영화',
    x: -110,
    y: -100,
    link: '/paper/movie',
    edges: ['타이타닉'],
    circleSize: 25,
  },
  타이타닉: {
    value: '타이타닉',
    x: -130,
    y: -150,
    link: '/paper/movie-titanic',
    edges: [],
    circleSize: 20,
  },
  뮤지컬: {
    value: '뮤지컬',
    x: 10,
    y: -95,
    link: '/paper/musical',
    edges: [],
    circleSize: 25,
  },
  '2학년 1, 2일': {
    value: '2학년 1, 2일',
    x: 120,
    y: 150,
    link: '/paper/first-day-2-years',
    edges: [],
    circleSize: 20,
  },
  'AI Club 🌿Fregic': {
    value: 'AI Club 🌿Fregic',
    x: -60,
    y: 200,
    link: '/paper/my-first-class-in-fregic',
    edges: ['Linear Regression PDF 자료'],
    circleSize: 20,
  },
  'Linear Regression PDF 자료': {
    value: 'Linear Regression PDF 자료',
    x: -49,
    y: 240,
    link: '/files/paper/my-first-class-in-fregic/LinearRegressionPDF.pdf',
    edges: [],
    circleSize: 15,
  },
  '../': {
    value: '../',
    x: -60,
    y: 50,
    link: '/mind-map/post',
    edges: [],
    circleSize: 32,
  },
  학업: {
    value: '학업',
    x: 100,
    y: 50,
    link: '/paper/나의-일상',
    edges: ['디미고'],
    circleSize: 40,
    isFolder: true,
  },
  '공업일반 1인 1프로젝트': {
    value: '공업일반 1인 1프로젝트: Pintos',
    x: 130,
    y: -80,
    link: '/mind-map/1-person-1-project',
    edges: ['학업'],
    circleSize: 30,
  },
  'PDF 발표 자료': {
    value: 'PDF 보고서 및 발표 자료',
    x: 260,
    y: -20,
    link: '/mind-map/1-person-1-project',
    edges: ['학업'],
    circleSize: 30,
    isFolder: true,
  },
  '진로 롤모델 발표 자료': {
    value: '진로, 롤모델 발표 자료: 데카르트.pdf',
    x: 320,
    y: 20,
    link: '/files/paper/dream/AboutDescartesWithMyThoughtPDF.pdf',
    edges: ['PDF 발표 자료'],
    circleSize: 10,
  },
  '자료구조 graph 발표 자료': {
    value: '자료구조, graph 발표 자료.pdf',
    x: 320,
    y: 60,
    link: '/files/paper/graph/graph.pdf',
    edges: ['PDF 발표 자료'],
    circleSize: 10,
  },
  '진로 연구 보고서: 행렬과 일차 방정식': {
    value: '진로, 연구 보고서: 행렬과 일차 방정식.pdf',
    x: 320,
    y: 100,
    link: '/files/paper/Matrix.pdf',
    edges: ['PDF 발표 자료'],
    circleSize: 10,
  },
  '미적분 발표 자료: 미분에 대한 고찰과 컴퓨팅에서의 응용': {
    value: '미적분, 발표 자료: 미분에 대한 고찰과 컴퓨팅에서의 응용.pdf',
    x: 320,
    y: 140,
    link: '/files/paper/derivative.pdf',
    edges: ['PDF 발표 자료'],
    circleSize: 10,
  },
};

export default function MyLife() {
  return <MindMap nodes={nodes} />;
}
