export const nodes = {
  'Machine Learning': {
    value: 'Machine Learning',
    x: 0,
    y: 0,
    link: 'Machine-Learning',
    edges: ['b', 'c'],
    circleSize: 60,
  },
  b: {
    value: '한글123English',
    x: -70,
    y: -50,
    link: 'b',
    edges: ['d', 'e'],
    circleSize: 20,
  },
  c: {
    value: '3',
    x: 60,
    y: 100,
    link: 'c',
    edges: [],
    circleSize: 20,
  },
  d: {
    value: '4',
    x: -140,
    y: -70,
    link: 'd',
    edges: [],
    circleSize: 27,
  },
  e: {
    value: '5',
    x: -20,
    y: -120,
    link: 'e',
    edges: [],
    circleSize: 20,
  },
};
